site_name: ELK

nav:
    - Home: 'index.md'
    - Pendahuluan: 'pendahuluan.md'
    - Instalasi:
        - Elasticsearch: 'elasticsearch.md'
        - Logstash: 'logstash.md'
        - Kibana: 'kibana.md'
    - Operasi: 
        - CRUD: 'crud.md'
        - Query Elasticsearch: 'query.md'
        - Konfigurasi Xpack Elasticsearch: 'conf_elastic.md'
        - Konfigurasi Xpack Kibana: 'conf_kibana.md'
        - Konfigurasi Pipeline Logstash: 'conf_logstash.md'
        - Instalasi Filebeat: 'filebeat.md'
        - Analisis Log 1: 'log1.md'
        - Analisis Log 2: 'log2.md'
    - Pengayaan:
        - Mengakses Elasticsearch: 'rich_elastic.md'
        - Elasticsearch Sebagai Secondary Database: 'secondary_db.md'
        - ELK Nginx Reverse Proxy: 'reverse_proxy.md'